### ISSUE TITLE
crash: mlt_animation_next_key

### ISSUE THREAD

**Issue by eszlari** [mltframework/mlt#339]
> Kdenlive Crashes when attempting to use "White Balance" color correction

https://github.com/flathub/org.kde.kdenlive/issues/10
```
#0  0x00007ffff71885f1 in mlt_animation_next_key (self=0x0, item=item@entry=0x7fffffffbf90, position=-1) at mlt_animation.c:527
#1  0x00007ffff6f5286a in Mlt::Animation::next_key(int) (this=<optimized out>, position=<optimized out>) at MltAnimation.cpp:109
#2  0x00000000005aa192 in KeyframeView::loadKeyframes(QLocale const&, QDomElement const&, int, int) ()
[...]
```

**Comment by faridosc** [comment]
I just tested 18.04.1 AppImage and it seems to work fine. Ar you using MLT 6.8 in the flatpak by any chance?

**Comment by eszlari** [comment]
Yes, see the MLT commit in https://github.com/flathub/org.kde.kdenlive/blob/master/org.kde.kdenlive.json

**Comment by faridosc** [comment]
AFAIK it is better to stick with MLT 6.6 for now until Kdenlive devs build it against a later version. (Just an opinion though.)

**Comment by eszlari** [comment]
This was fixed in kdenlive: https://github.com/KDE/kdenlive/commit/9b09dbb2b0de78d4eaf4011c8a462fdb3c6916b6

**Comment by lukefromdc** [comment]
Still getting crashes with mlt master on opening a very large and complex file. Effects include "lift-gamma-gain," "position and zoom" and many others. Can't post the file itself as some of the raw clips are sensitive along with their filenames.
