### ISSUE TITLE
Audio effects not starting at clip start, resulting in audio click

### ISSUE THREAD

**Issue by j-b-m** [mltframework/mlt#566]
Hi again,
Following issue #564, the original reporter found another issue, this time affecting audio effects.
In some cases, the audio effect does not seem to be applied at the very start of the clip, leaving a few milliseconds of original audio, leading to clicks. This seems to happen only in playlists when several clips are on a track mixed with another.

You can reproduce using the reporter files in melt.
Source files:
https://bugs.kde.org/attachment.cgi?id=128621
Melt command:
melt -profile ./customprofile32 audio-source.mp3 -track -blank 95 bj_helm1.wav -attach volume gain=0 -transition mix sum=1 -consumer avformat:test3.wav channels=1

Playlist looks like in screenshot.
![playlist](https://user-images.githubusercontent.com/108252/82427719-c2588680-9a89-11ea-92b2-0f76b6ff6ee0.png)

 and you can compare the result in audacity. First one is rendered without effects, second one has a "mute" effect applied to second clip from first track and you can see the "click"; which seems to be the first original milliseconds without effect applied.

![audacity-compare](https://user-images.githubusercontent.com/108252/82427748-cd131b80-9a89-11ea-8a63-f4e8fcc19093.png)

I tested several audio effects, they all seem to have to offset issue.

**Comment by ulatekh** [comment]
I'm the original reporter. Can you give me some hints on how I might track this down myself? I've been going through hell trying to understand the undocumented mlt source code.

My best idea so far is to use something like libsndfile to write the input/output audio streams from every service involved with the above command-line, in the hopes that I'll at least figure out what stage is causing the problem.

**Comment by ddennedy** [comment]
It is not easy to debug this. Step 1 is to reproduce it. I did not reproduce it with the command line above. I did reproduce it with the project file.
The next step is to simplify and reduce the composition to narrow it down. For starters, I remove the muted hidden track. I am editing the XML to make experiments, and that is noise. I still reproduce it.
If I disable the mix transitions the problem goes away for me. That is a big hint. I turn that back on to make more experiments.
Make hypotheses and test them. For example, maybe the overlapping volume filters on the `bj_helm1.wav` clips are a problem. Disable the ones that are set to 0.5 gain.
And so on. At some point you get into code, and I might add additional debug log lines or change the level of existing ones to get more information. Keep making experiments; trial and error....

**Comment by ulatekh** [comment]
I apologize for not making it easier to reproduce. That was the minimal .mlt file I could generate that still reproduced the problem.

And I understand how to debug things in general, just not in the wild & wooly mlt code. But it sounds like tracking this one is difficult for you too, so that makes me feel better. :-) Thank you for starting to look at it!

**Comment by ddennedy** [comment]
The attached XML is a minimal project the reproduces it for me with obvious artifacts at 2.086s and 3.347s. That corresponds to frames 47 and 76, which coincides with the beginning of the last two clips of `32_playlist1`/`bj_helm1.wav`. The clips only have one volume filter with gain=0 on them. Disabling the transition0 (mp3 with black background) makes the problem go away. Until further debugging is done, it would be good if you can confirm that disabling that transition in your test project prevents it for you as well.


[audio-artifact-ddennedy-1-mltxml.txt](https://github.com/mltframework/mlt/files/4670669/audio-artifact-ddennedy-1-mltxml.txt)

**Comment by ulatekh** [comment]
For the record, my command line is `./src/melt/melt -profile ./customprofile32 xml:audio-artifact-ddennedy.mlt properties=WAV -consumer avformat:audio-artifact.wav ar=44100`, run from the top-level mlt source directory, as well as from the CMake-generated build directory.

I find that I have to disable transition1 (i.e. change the value of `<property name="disable">` from 0 to 1) to get the artifact to go away. If I just disable transition 0, the artifact is still there, twice.

Also, for me, the audio is twice-speed and choppy; see the attached screenshot. But one crippling bug at a time. :-)

![audio-artifact](https://user-images.githubusercontent.com/908096/82716258-6fc6c800-9c4b-11ea-8dcb-b897508ce0af.png)

**Comment by ddennedy** [comment]
I was also able to reproduce it by replacing `bj_helm1.wav` with a `silence.wav` that has the same attributes (mono 22050 Hz) and removing all of the volume filters. This is looking like a transition mix problem. 
[audio-artifact-ddennedy-2-mltxml.txt](https://github.com/mltframework/mlt/files/4670770/audio-artifact-ddennedy-2-mltxml.txt)

**Comment by ddennedy** [comment]
> I find that I have to disable transition1 (i.e. change the value of <property name="disable"> from 0 to 1) to get the artifact to go away. If I just disable transition 0, 

How else to disable other than set disable=1? Did you mean "If I just remove transition 0?"

**Comment by ulatekh** [comment]
>How else to disable other than set disable=1? Did you mean "If I just remove transition 0?"

Remember, you're a lot more fluent with raw mlt files than I am. :-)

**Comment by ddennedy** [comment]
`properties=WAV` is in the wrong position. It goes after the `-consumer avformat`

**Comment by ulatekh** [comment]
I didn't know my command-line arguments were wrong. Others have commented about mlt's lack of [error](https://github.com/mltframework/mlt/issues/123) [reporting](https://github.com/mltframework/mlt/issues/165). I'm doing the best I can in an information-deprived environment.

**Comment by ddennedy** [comment]
Please test branch [bug566](https://github.com/mltframework/mlt/tree/bug566). It is significantly improved for me on removing clicks around silence parts, but it may not still be perfect. 
Here is now I run it
`melt -silent -verbose xml:audio-artifact-ddennedy-1-mltxml.txt out=127 -consumer avformat:test.wav channels=1`

**Comment by ulatekh** [comment]
I still get the same audio artifacts, at 1.517s and 2.517s.
![artifacts-1 517s-2 517s](https://user-images.githubusercontent.com/908096/82737354-6d18b100-9ce5-11ea-8442-8a841943e4de.png)

**Comment by ddennedy** [comment]
I pushed another commit to the branch to add more comments to explain what the transition code is doing. It also has some code that you can activate with a #define for a simpler approach (KISS) that has its own flaws with respect to A/V sync. However, it is useful as a debugging tool to set the define and run a test to observe that a problem goes away. It does for me in this test case indicating a problem likely somewhere in this code. I am just not seeing it. Maybe someone else will.

**Comment by j-b-m** [comment]
Sorry, I made many tests and my melt command in the original report was wrong. To reproduce, I used:
melt -profile ./customprofile32 audio-source.mp3 -track -blank 48 bj_helm1.wav in=0 out=7 -blank 39 bj_helm1.wav -attach volume gain=0 -transition mix sum=1 -consumer avformat:result.wav channels=1

I just tested the latest commits to your bug566 branch and it fixes the issue for me (above is result with mlt git master and below with your latest bug566 branch) - the click around the middle disappeared.
![Screenshot_20200523_220231](https://user-images.githubusercontent.com/108252/82739617-1fca2d00-9d41-11ea-9b6d-3241604c2376.png)

**Comment by ulatekh** [comment]
I'm using the same command line I was given before:

`./src/melt/melt -silent -verbose xml:audio-artifact-ddennedy.mlt -out 127 -consumer avformat:audio-artifact.wav channels=1`

and I still see artifacts. (I posted a close-up picture of the artifacts earlier today.)

So perhaps one audio-artifact bug was fixed, but there are more.

**Comment by bmatherly** [comment]
This reminds me of the problem we were having with the pitch filter that would cause problems if the filter did not return the exact number of samples requested. In that case, we repeated or discarded samples to make up the difference.

Here is a patch that recreates the same effect for the resample filters:
https://github.com/bmatherly/mlt/commit/03085496dcfd0ddcd48556b67e9c04d35551c5e3

In my testing, the artifacts were gone with this change. Maybe others could try it and see if it improves for them.

**Comment by ddennedy** [comment]
There is more that I have not found because even after I make my fix, I hear a couple in the active audio areas. The new logic to silence buffered samples upon a discontinuity is logically necessary because image the simple scenario clip A followed by some blank followed by clip B. The mix transition is not called during the blank spot. Thus leftover samples from clip A should not be mixed as-is on the first frame of clip B. Hence, the change detects this and silences the buffered samples. The problem is that even when I replaced the `bj_helm1.wav` sound effect with a silence audio file, where did these non-silent samples come from?

**Comment by ulatekh** [comment]
@bmatherly: For some reason, I can't get your commit, even after adding your branch as a remote and fetching. But I can apply it by hand. In any case, the artifacts in the test sample are gone! I'm going to test my video projects (including some old ones) to see what it does for my known artifacts.

**Comment by ulatekh** [comment]
@bmatherly: OMG...that took care of nearly every audio artifact I've had in my projects for the last 9 months! (I made a list of all the pops I could find, so I could use audacity's "repair" feature to cover them up. So I knew where to look.) The only remaining ones were ones I could never spot in the waveform; it's hghly likely they weren't digital artifacts to begin with, but some consequence of my source audio.

Thank you so much for your help with this! I am in your debt.

**Comment by ddennedy** [comment]
Brian's patch is working well for me too. I merged into my local branch that has my other fix. I will do some long duration A/V sync testing before merging all these to master and resolving.

**Comment by bmatherly** [comment]
>  I will do some long duration A/V sync testing before merging all these to master and resolving.

I wonder if we should consider adding some debug or info messages in the discard/repeat sample cases so that we can see how often that is being triggered. I would leave that up to you.

**Comment by ddennedy** [comment]
merged c41963c8cca02f64a682896281c47f6a543c6654 and 7f0194f9858088b53ce76c815a2aa8cc18b0148a as well
